export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  mailHost: process.env.MAIL_HOST ?? "",
  mailPort: process.env.MAIL_PORT ? parseInt(process.env.MAIL_PORT, 10) : 465,
  mailUser: process.env.MAIL_USER ?? "",
  mailPassword: process.env.MAIL_PASSWORD ?? "",
  mailFrom: process.env.MAIL_FROM ?? "noreply@kaffeegraf.coffee",
  mailTestMode: process.env.MAIL_TEST_MODE === "true",
  mailTestInbox: process.env.MAIL_TEST_INBOX ?? "",
  mailinatorApiToken: process.env.MAILINATOR_API_TOKEN ?? "",
};
